/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#FFE8A3",
        "on-primary-fixed-variant": "#6E3B00",
        "secondary-container": "#FFE8D6",
        "surface-tint": "#C68B59",
        "surface-variant": "#F5EFE4",
        "surface-dim": "#EFEAE0",
        "outline": "#8E8276",
        "on-surface-variant": "#5C5248",
        "on-primary-container": "#5E3000",
        "background": "#FAF6EE",
        "on-secondary-fixed-variant": "#52321A",
        "surface-container-lowest": "#FFFFFF",
        "inverse-primary": "#FFB066",
        "inverse-surface": "#2A251F",
        "primary-fixed": "#C68B59",
        "secondary": "#A98467",
        "error": "#E76F51",
        "on-tertiary-container": "#2F2B18",
        "primary-container": "#FFE8D6",
        "on-secondary-container": "#52321A",
        "on-tertiary": "#4A452B",
        "primary-fixed-dim": "#B57A48",
        "surface-container-low": "#FAF6EE",
        "error-dim": "#C94A29",
        "surface-container-high": "#EFEAE0",
        "tertiary-dim": "#E0DCC2",
        "on-tertiary-fixed-variant": "#4A452B",
        "tertiary-container": "#FFE8A3",
        "surface": "#FAF6EE",
        "on-secondary-fixed": "#52321A",
        "error-container": "#801D05",
        "on-error": "#FFFFFF",
        "on-background": "#2A251F",
        "tertiary": "#F4F1DE",
        "on-primary": "#FFFFFF",
        "primary-dim": "#B57A48",
        "surface-container": "#F5EFE4",
        "on-surface": "#2A251F",
        "on-error-container": "#FFD9D2",
        "tertiary-fixed-dim": "#E0DCC2",
        "primary": "#C68B59",
        "surface-container-highest": "#E7E1D5",
        "surface-bright": "#FFFFFF",
        "on-secondary": "#FFFFFF",
        "secondary-dim": "#8F6A4E",
        "outline-variant": "#D0C5B8",
        "secondary-fixed": "#FFE8D6",
        "secondary-fixed-dim": "#E6CCB2",
        "on-tertiary-fixed": "#2F2B18",
        "inverse-on-surface": "#FAF6EE",
        "on-primary-fixed": "#3D1F00"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "display": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "12px", "lg": "16px", "xl": "24px", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
